### ISSUE TITLE
excript: exception error - in projs using sqlight and building using gleescript

### ISSUE THREAD

**Issue by hammad-r-javed** [lpil/gleescript#3]
When building (using -m gleescript) code that includes sqlight, the following error can be observed on the macOS m1 platform (have not tested other platforms yet)
`escript: exception error: undefined function esqlite3_nif:open/1`

Platform: macOS m1
Erlang version: Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 14.1
Rebar3 verson: rebar 3.22.1 on Erlang/OTP 26 Erts 14.1
Gleam version: v1.0.0 (pre-built binary)
Sqlite3 is installed on the system.

Current hacky solution is to do the following:
1. `gleam build`
2. `gleam run -m gleescript`
3. Manually copy the `<project name>build/dev/erlang/esqlite/priv/esqlite3_nif.so` shared object file to `./priv/esqlite3_nif.so`, which is a relative path to the generated executable.

**Comment by lpil** [comment]
Hello! Erlang escripts do not support code written in C so SQLite is not usable with them.

Perhaps in future they might, but as far as I'm aware it has not been requested of the Erlang team.

**Comment by hammad-r-javed** [comment]
Ahhh I see, thanks for the clarification!
